name: shadowsocks
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  simple_rc4: ^0.1.6
  crypto: ^2.1.5
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
